### ISSUE TITLE
LoadError: cannot load such file -- ravendb

### ISSUE THREAD

**Issue by stevanmarjanovic** [ravendb/ravendb-ruby-client#45]
I installed RavenDB Ruby Client with `sudo gem install ravendb` (without `--save` flag because it returns invalid option error).
I have a Ruby file which only requires ravendb and when I run `ruby main.rb` I get the following error:
```ruby
Traceback (most recent call last):
	2: from main.rb:1:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ravendb (LoadError)
```
There is something wrong with README file of this repository, it doesn't provide correct setup guide for connecting to database.

**Comment by ppekrol** [comment]
Hi @marjanovicsteva 

We never finalized the work on the Ruby Client for RavenDB and halted the development mid-run. At this point we are looking for Community assistance on this project.
